/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.35.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

export type { CounterAbi } from './CounterAbi';

export { CounterAbi__factory } from './factories/CounterAbi__factory';
